### ISSUE TITLE
use application.android.startActivity instead of foregroundActivity

### ISSUE THREAD

**Issue by NickIliev** [tylergrinn/nativescript-plugin-google-places#4]
Related to [this issue](https://github.com/NativeScript/NativeScript/issues/5307#issuecomment-359341298)

You might want to [change this line](https://github.com/tylergrinn/nativescript-plugin-google-places/blob/cbb97821e27c624ed57bc353a2bda1d478dc8758/src/plugin-google-places.android.ts#L45) to use `startActivity` on this line to ensure that the `Activity` is not `undefined` for the reasons discussed in the linked issue.

**Comment by EddyVerbruggen** [comment]
@NickIliev Note that there's a deprecation warning for `startActivity` in the sourcecode. That being said I've changes 4 or 5 plugins to use it because NativeScript 3.4 kinda broke `foregroundActivity` in the sense that it's now available later in the app's lifecycle than it used to be.

**Comment by NickIliev** [comment]
@EddyVerbruggen thanks for pointing that out - will investigate further if we need to rethink the `foregroundActivbity` lifecycle or perhaps rethink the deprecation of `startActivity`.

**Comment by penguin-007** [comment]
I have the same problem
